### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/cornell_train.txt'

### ISSUE THREAD

**Issue by saran-gangster** [jkarimi91/chatbot#4]
Getting data...
Tokenizing...
Filtering...
Saving...
Traceback (most recent call last):
  File "H:\python\artificialintelligence\J.A.R.V.I.S\chat bot to me\chatbot-master\process_cornell.py", line 86, in <module>
    save_data(train, ENCODING, TRAIN_PATH)
  File "H:\python\artificialintelligence\J.A.R.V.I.S\chat bot to me\chatbot-master\utils.py", line 50, in save_data
    with open(file_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/cornell_train.txt'

**Comment by saran-gangster** [comment]
please help with this
